version: "3"

services:
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474
      - 7687
    environment:
      - NEO4J_AUTH=neo4j/123haslo123
    volumes:
      - $HOME/zip-app/backend/neo4j/data:/data
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - PORT=8080
      - NEO4J_PASSWORD=123haslo123
      - CLIENT=frontend
      - NEO4J_USERNAME=neo4j
      - NEO4J_HOST=neo4j
    ports:
      - 8080
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    environment: 
      - VITE_API_HOST=localhost
    ports:
      - 80:80
